Handle distinct error conditions uniquely
logzio/fluent-bit-logzio-output pull request #7
Opened 2020-08-24 02:33 UTC by alexjurkiewicz

Lines like this in the error output are not so useful:

```
2020/08/24 02:20:35 [logzio] recieved an error from logz.io listener: <nil>
2020/08/24 02:20:39 [logzio] recieved an error from logz.io listener: <nil>
```

2020-08-24 05:54 UTC, idohalevi requested changes
@alexjurkiewicz Looks good. Please add the response message as well to the output

2020-08-24 06:09 UTC, alexjurkiewicz commented
Do you mean the response body? And on line 172?

2020-08-24 06:20 UTC, idohalevi commented
> Do you mean the response body? And on line 172?

Yes. The listener response message might contain useful debugging information about the reason for the failure

2020-08-24 06:36 UTC, alexjurkiewicz commented
OK. I'm not that familiar with Go, and I'm editing in the GitHub UI, so please double check my work 🙏

2020-08-31 10:17 UTC, mirii1994 commented
Response body was translated to a decimal array, fixed it to appear as a string.

2020-09-01 13:49 UTC, mirii1994 approved these changes

2020-09-01 13:49 UTC, merged